[package]
name = "steghunt"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
sha256 = { version = "1.0.3" }
crossterm = { version = "0.23" }
which = { version = "4.2.5" }
